### ISSUE TITLE
BUG _ created_by unnecessary for tags

### ISSUE THREAD

**Issue by DihiaMezghiche** [usealto/bubble#10]
![image](https://user-images.githubusercontent.com/82890372/210739747-d24910b5-8e1d-4d33-a59c-edacf764117a.png)

The element col_created_by, in the Tag table, is trying to retrieve a user, but there is no ID of the user that should be retrieved.

**Comment by sbounmy** [comment]
fixed by using a condition instead of sending a no_user id 

![Image](https://user-images.githubusercontent.com/159814/210751806-0930a5be-cbbb-4f0d-ab5f-8e513f8ab802.png)
