### ISSUE TITLE
BUG menu

### ISSUE THREAD

**Issue by guillim** [usealto/bubble#15]
As you can see, there is some weird display in the menu when Romain uses alto.

Laptop : Windows
Context  : Google Chrome (up to date)
Zoom : 100%
User : romain-demo
Version : app.usealto.com/
Clean du cache fait

- Loading bar en the left ? 
- no display of some elements [We investigated and the "Gamification" label looks empty...]

<img width="1479" alt="Screenshot 2023-01-06 at 18 38 35" src="https://user-images.githubusercontent.com/13087916/211067584-5c9bea41-964c-48b4-8a4d-dc0e4480ff53.png">

**Comment by guillim** [comment]
We found out that is happens when the menu gets too small (in height)

**Comment by Mihajahackerhouse** [comment]
I reduced the margins between elements in the group
- 15 px between icon and title
-  2 px between title and right block.

![image](https://user-images.githubusercontent.com/112725844/211264629-d282ff3a-df9d-4ed0-b5c2-c37f2fc15f24.png)

![image](https://user-images.githubusercontent.com/112725844/211264704-79dea3c5-27e3-4a1e-9e48-8c3597c94763.png)

@guillim @DihiaMezghiche @sbounmy

**Comment by guillim** [comment]
=> Would be good to hide the "Envoyer votre feedback" if "height" gets too small and triggers the scroll bar in the menu
