### ISSUE TITLE
🐛 [bug]: anchor forgotten "Questions en attente"

### ISSUE THREAD

**Issue by guillim** [usealto/bubble#23]
## Is there an existing issue for this?

Please make a search to see if an issue related to this feature request already exists.

- [ ] I have searched the existing issues

## Current behavior

As a lead, when I click on "Questoins en atente" on the programme page, it does not send me to the bottom of the page 

- [x] Screenshot  
<img width="1050" alt="Screenshot 2023-01-12 at 14 07 34" src="https://user-images.githubusercontent.com/13087916/212074710-e09a18a0-b09d-48c6-b75f-da45f34b9189.png">

  
## Steps to reproduce

Add steps to reproduce this behaviour, include console or network logs and screenshots:

1. Go to [programme](https://app.usealto.com/version-live/l?debug_mode=true)
2. Click on "Questions en attente"
3. notihng happpens while it should

## Environment

- [ ] test (version-test)
- [x] live (version-live)

**Comment by Mihajahackerhouse** [comment]
Problem: No workflow on button

Solution: Put a workflow scroll to "section_question.submitted"

Problem fixed in "version-test"

Waiting for a deployment for the live version
