### ISSUE TITLE
Remove the obligation of reload to display a new team

### ISSUE THREAD

**Issue by LyzaMessadene** [usealto/bubble#34]
https://www.notion.so/usealto/When-creating-a-new-team-I-have-to-reload-the-page-to-have-it-accessible-in-the-User-edition-view-87f5b648339c446984e443223df64b60

**Comment by Mihajahackerhouse** [comment]
Issue : 
reusable element not refreshed

Solution : 
Put the data source in a condition

@guillim @sbounmy
