### ISSUE TITLE
🐛 [bug]: <Get some more cheerful & positive colors on our dashboards>

### ISSUE THREAD

**Issue by Romaineli** [usealto/bubble#43]
Thank you for taking the time to fill out this bug report properly.

## Is there an existing issue for this?

Please make a search to see if an issue related to this feature request already exists.

- [X] I have searched the existing issues

## Current behavior

A concise description of what you're experiencing, when logged in as a lead/memeber..., and what you expect:

As an <Admin> and a <User>, when I log in for the first times on the App i feel like a little bit opressed by all the orange and red colors. It's not very friendly and welcoming.  
```...```  
What I expect is to have more <positive> colors on the most part of our KPIs and dashboard and i first connect and before my team start to use Alto and even if i don't have any (positive) data to display.

We could, with @Pierre @usealto/freelances, enhance this aspect.

- [X] Screenshot  

Screenshots are welcomed ! They are very easy to understand and provode context. But make sure there are no Secret Key / or email in the screenshot

<img width="423" alt="dsfsdfsdfsdsdfds" src="https://user-images.githubusercontent.com/122815339/214877091-f57f5ebf-99ea-4ce8-9724-fa58eede2316.PNG">

**Comment by guillim** [comment]
Could you imagine how you would improve the current screens @Romaineli  ? Maybe with Pierre help ? Like precisey step by step ? It's a bit too vague at the moment to begin implementation
