### ISSUE TITLE
moderation : Comment

### ISSUE THREAD

**Issue by sbounmy** [usealto/bubble#6]
https://www.figma.com/file/SaBUBmTStDOCmzH6Wy39H1/Alto-Assessment?node-id=503%3A194111&t=5GmlAeWqblCvLhQo-0

## /u
Deja présent "petit commentaire" qui slide dans flg_result

<img width="348" alt="CleanShot 2023-01-02 at 11 14 18@2x" src="https://user-images.githubusercontent.com/159814/210218015-d1aa976d-abc7-4c35-9aae-068df763af64.png">

## /l

- Faire le floating group dans `flg` comme les autres
- Ajouter un champ question dans comment 
- Supprimer Question#Comments (list)
- Popup confirmation suppression commentaire
<img width="789" alt="CleanShot 2023-01-02 at 11 19 33@2x" src="https://user-images.githubusercontent.com/159814/210218530-db4adef9-5bab-4a6a-9232-df0c267e23c4.png">
- Rajouter un yes/no "Marked as Read"
- Page commentaire
- filtre lu/non lu

**Comment by DihiaMezghiche** [comment]
@sbounmy @guillim Donc voila pour ce ticket, en attente de vos commentaires.

https://www.loom.com/share/beaf591a587f43698a542fd910e89a7e

**Comment by guillim** [comment]
> https://www.loom.com/share/beaf591a587f43698a542fd910e89a7e

Could you add some difference in the background color to ressemble a bit more to gmail style in read VS unread mail ?
<img width="366" alt="Screenshot 2023-01-03 at 18 26 17" src="https://user-images.githubusercontent.com/13087916/210409339-a452bb39-90b5-438b-99e8-a27716434cb2.png">

**Comment by guillim** [comment]
Another "visual"  request : is it possible to align some elements ?

I am talking about the
- checkbox in the filters "read" "unread"
-the profil pic in case there is only one line like in your example.

<img width="2581" alt="Screenshot 2023-01-03 at 18 32 27" src="https://user-images.githubusercontent.com/13087916/210410422-98d629a5-f5aa-4bdf-ab87-79544ef8fc78.png">

**Comment by DihiaMezghiche** [comment]
Good evening, for the visual corrections you requested yesterday.  Attached to this comment are some screenshots.

- [ ]  Difference in the background color to ressemble a bit more to gmail style in read VS unread.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/82890372/210551679-034f1edb-b76d-46f9-afd6-b6782cf8d7fa.png">

- [ ]  Element alignment : 
![image](https://user-images.githubusercontent.com/82890372/210551926-9f98ebb9-51c0-48d6-9277-344e76e34a0b.png)

![image](https://user-images.githubusercontent.com/82890372/210552048-53973d10-95b3-474d-947d-cf6229e0f946.png)


@sbounmy  @guillim

**Comment by guillim** [comment]
sounds good to me !
